### ISSUE TITLE
it\'s error on install

### ISSUE THREAD

**Issue by guohuihot** [nfroidure/gulp-iconfont#101]
npm install --save gulp-iconfont

```
> ttf2woff2@2.0.3 install E:\ats08\node_modules\gulp-iconfont\node_modules\gulp-ttf2woff2\node_modules\ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

module.js:338
    throw err;
    ^

Error: Cannot find module 'D:\Program'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
gulp-iconfont@5.0.1 node_modules\gulp-iconfont
├── gulp-cond@1.0.0 (readable-stream@2.0.5)
├── streamfilter@1.0.5 (readable-stream@2.0.5)
├── plexer@1.0.1 (isstream@0.1.2, readable-stream@2.0.5)
├── gulp-ttf2eot@1.1.1 (bufferstreams@1.1.0, readable-stream@2.0.5, ttf2eot@1.3.0)
├── gulp-ttf2woff@1.1.0 (bufferstreams@1.1.0, readable-stream@2.0.5, ttf2woff@1.3.0)
├── gulp-spawn@0.3.0 (plexer@0.0.1, gulp-util@2.2.20)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, fancy-log@1.1.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, gulplog@1.0.0, lodash.template@3.6.2, vinyl@0.5.3, through2@2.0.0, chalk@1.1.1, multipipe@0.1.2, dateformat@1.0.12)
├── gulp-svgicons2svgfont@2.4.0 (readable-stream@2.0.5, svgicons2svgfont@3.2.0)
├── gulp-svg2ttf@1.1.5 (bufferstreams@1.1.0, readable-stream@2.0.5, svg2ttf@2.1.1)
└── gulp-ttf2woff2@2.0.2 (bufferstreams@1.1.0, readable-stream@2.0.5, ttf2woff2@2.0.3)

```

**Comment by nfroidure** [comment]
This is an error but i doesn't affect the plugin behavior since the is a fallback in cas of compilation error.
