### ISSUE TITLE
ttfauthint EPIPE error on windows

### ISSUE THREAD

**Issue by DSteinmann** [nfroidure/gulp-iconfont#132]
Hi, 

First of all: thanks for your work! 
I'm having some difficulties building an iconfont with the autohint option enabled. I've installed ttfautohint and added it to my path variables but i keep getting the following error: 

```
C:\Users\dominik.steinmann\Web\node_modules\ttf2woff2\jssrc\ttf2woff2.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSy

Error: write EPIPE
    at exports._errnoException (util.js:1036:11)
    at Socket._writeGeneric (net.js:705:26)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at PassThrough.stream._transform (C:\Users\dominik.steinmann\Web\node_modules\gulp-spawn\index.js:84:18)
    at PassThrough.Transform._read (_stream_transform.js:167:10)
    at PassThrough.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at PassThrough.Writable.write (_stream_writable.js:220:11)
    at StreamFilter.ondata (C:\Users\dominik.steinmann\Web\node_modules\streamfilter\node_modules\readable-stream\lib\_stream_readable.js:542:20)
    at emitOne (events.js:96:13)
    at StreamFilter.emit (events.js:188:7)
    at readableAddChunk (C:\Users\dominik.steinmann\Web\node_modules\streamfilter\node_modules\readable-stream\lib\_stream_readable.js:213:18)
    at StreamFilter.Readable.push (C:\Users\dominik.steinmann\Web\node_modules\streamfilter\node_modules\readable-stream\lib\_stream_readable.js:172:10)
    at StreamFilter.Transform.push (C:\Users\dominik.steinmann\Web\node_modules\streamfilter\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at StreamFilterCallback (C:\Users\dominik.steinmann\Web\node_modules\streamfilter\src\index.js:30:15)
    at filter.objectMode (C:\Users\dominik.steinmann\Web\node_modules\gulp-iconfont\src\index.js:34:9)
    at StreamFilter.streamFilterTransform [as _transform] (C:\Users\dominik.steinmann\Web\node_modules\streamfilter\src\index.js:28:5)
```

My config is: 

```
iconFontConfig: {
            fontName: 'IconFont',     // required
            prependUnicode: true,            // recommended option
            formats: ['ttf', 'eot', 'woff'], // default, 'woff2' and 'svg' are available
            timestamp: runTimestamp,         // recommended to get consistent builds when watching files,
            autohint: true,
            normalize: true,
            fontHeight: 1001
        },
```

Did anybody experience the same issue?

**Comment by nfroidure** [comment]
Closing since old and probably a ttfautohint install issue.
