### ISSUE TITLE
Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by lovik1468** [nfroidure/gulp-iconfont#154]
At me a problem on Windows all worked ideally but when I launched this script on Ubuntu the error at creation of a font constantly flies. Can you tell me what might be the problem

That's what he writes to me
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
:~/work/alscon_gulp_bild-master$ gulp iconfont
[16:40:39] Using gulpfile ~/work/alscon_gulp_bild-master/gulpfile.js
[16:40:39] Starting 'iconfont'...
[16:40:39] gulp-svgicons2svgfont: Font created

events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at Transform.svg2ttfTransformStream [as _transform] (/home/lovik/work/alscon_gulp_bild-master/node_modules/gulp-svg2ttf/src/index.js:87:32)
    at Transform._read (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at Transform._write (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Transform.Writable.write (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Duplexer.ondata (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:77:13)
    at Duplexer.emit (events.js:169:7)
    at addChunk (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at Duplexer.Readable.push (/home/lovik/work/alscon_gulp_bild-master/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at Duplexer._pushAll (/home/lovik/work/alscon_gulp_bild-master/node_modules/gulp-svgicons2svgfont/node_modules/plexer/src/index.js:105:31)
    at PassThrough.<anonymous> (/home/lovik/work/alscon_gulp_bild-master/node_modules/gulp-svgicons2svgfont/node_modules/plexer/src/index.js:82:13)
    at emitNone (events.js:67:13)
+++++++++++++++++++++++++++++++++++++++++++++++

Here is the code that is responsible for this task

gulp.task('iconfont', function () { // svg font
   var processors = [
                assets({
                    loadPaths: ['dist/fonts/', 'dist/img/', 'dist/img_clients/'],
                    basePath: 'dist/',
                    relative: true
                })
            ]
            return gulp.src('dev/icons/*.svg')
                .pipe(iconfont({
                    fontName: 'custom-icons',
                    formats: ['ttf', 'eot', 'woff', 'woff2'],
                    appendCodepoints: true,
                    appendUnicode: false,
                    normalize: true,
                    fontHeight: 1000,
                    centerHorizontally: true
                }))
                .on('glyphs', function (glyphs, options) {
                    gulp.src('dev/css/template/*.css')
                        .pipe(consolidate('underscore', {
                            glyphs: glyphs,
                            fontName: options.fontName,
                            fontDate: new Date().getTime()
                        }))
                        .pipe(gulp.dest('dev/css/'))
                        .pipe(postcss(processors));
                  gulp.src('dev/icons/template_html/index.html')
                        .pipe(consolidate('underscore', {
                            glyphs: glyphs,
                            fontName: options.fontName
                        }))
                        .pipe(gulp.dest('dist/preview'));
                })
                .pipe(gulp.dest('dist/fonts'));
        });

**Comment by NaridaL** [comment]
node version?

**Comment by lovik1468** [comment]
v4.2.6

**Comment by NaridaL** [comment]
Does that version support typed arrays? That seems like the issue...

According to the package.json
"node": ">= 6.11.1"

**Comment by lovik1468** [comment]
I need to fix a more recent version of node.js?

**Comment by SebastienElet** [comment]
@lovik1468 you should switch to node 8, the end of maintenance for v4 will be in April 2018.

See https://github.com/nodejs/Release

**Comment by nfroidure** [comment]
Closing since the NodeJS version were unsupported and no news for a while.
