### ISSUE TITLE
Error on create fonts from svg

### ISSUE THREAD

**Issue by DanielBotea** [nfroidure/gulp-iconfont#167]
When I add a new svg or replace an old svg I have this error

12:50:17] Starting 'iconfont'...
[12:50:17] Finished 'iconfont' after 90 ms
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Invalid attribute name
Line: 3
Column: 1
Char: <
    at error (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/sax/lib/sax.js:1313:13)
    at SAXStream.write (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/sax/lib/sax.js:239:18)
    at PassThrough.ondata (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at PassThrough.emit (events.js:180:13)
    at PassThrough.Readable.read (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/readable-stream/lib/_stream_readable.js:462:26)
    at flow (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/readable-stream/lib/_stream_readable.js:806:34)
    at resume_ (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/readable-stream/lib/_stream_readable.js:789:3)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Emitted 'error' event at:
    at Duplexer._writable.on.err (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/plexer/src/index.js:63:13)
    at Duplexer.emit (events.js:180:13)
    at PassThrough.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/gulp-svgicons2svgfont/node_modules/plexer/src/index.js:63:13)
    at PassThrough.emit (events.js:180:13)
    at SVGIcons2SVGFontStream.fontStream.on (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/gulp-svgicons2svgfont/src/index.js:87:22)
    at SVGIcons2SVGFontStream.emit (events.js:180:13)
    at SAXStream.saxStream.on (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/svgicons2svgfont/src/index.js:258:12)
    at SAXStream.emit (events.js:185:15)
    at SAXParser.SAXStream._parser.onerror (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/sax/lib/sax.js:194:10)
    at emit (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/sax/lib/sax.js:624:35)
    at error (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/sax/lib/sax.js:653:5)
    at strictFail (/Applications/XAMPP/xamppfiles/htdocs/new-cfdglobal/node_modules/sax/lib/sax.js:677:7)
    [... lines matching original stack trace ...]
    at PassThrough.emit (events.js:180:13)

**My setup**
var iconFontTask = function (website) {
    gulp.src([resourcesPath + website + '/fonts/svg/*.svg'])
        .pipe(iconfontCSS({
            fontName: website,
            targetPath: '../../../' + resourcesPath + website + '/sass/_iconfont.scss',
            fontPath: '../fonts/',
            cssClass: website
        }))
        .pipe(iconfont({
            fontName: website,
            // Remove woff2 if you get an ext error on compile
            formats: ['svg', 'ttf', 'eot', 'woff', 'woff2'],
            normalize: true,
            fontHeight: 1001,
            prependUnicode: true,
        }))
        .pipe(gulp.dest(publicPath + website + '/fonts'));
};

node: v9.10.1
npm: 6.1.0

**Comment by DanielBotea** [comment]
Fix it!
