### ISSUE TITLE
ttf2woff2 installation fails

### ISSUE THREAD

**Issue by Danetag** [nfroidure/gulp-iconfont#61]
I kept searching on the internets, I could't find any solution for this one :(

```
$npm install gulp-ttf2woff2
 
> ttf2woff2@1.1.0 install /Users/danetag/Sites/tests/screwdriver/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc:9:20: error: unknown type name 'FunctionCallbackInfo'
void Convert(const FunctionCallbackInfo<Value>& args) {
                   ^
../csrc/addon.cc:9:40: error: expected ')'
void Convert(const FunctionCallbackInfo<Value>& args) {
                                       ^
../csrc/addon.cc:9:13: note: to match this '('
void Convert(const FunctionCallbackInfo<Value>& args) {
            ^
../csrc/addon.cc:11:15: error: no matching constructor for initialization of
      'v8::HandleScope'
  HandleScope scope(isolate);
              ^     ~~~~~~~
/Users/danetag/.node-gyp/0.10.35/deps/v8/include/v8.h:473:3: note: candidate
      constructor not viable: no known conversion from 'v8::Isolate *' to
      'const v8::HandleScope' for 1st argument
  HandleScope(const HandleScope&);
  ^
/Users/danetag/.node-gyp/0.10.35/deps/v8/include/v8.h:448:3: note: candidate
      constructor not viable: requires 0 arguments, but 1 was provided
  HandleScope();
  ^
../csrc/addon.cc:13:7: error: use of undeclared identifier 'args'; did you mean
      'uv_process_options_s::args'?
  if (args.Length() < 1) {
      ^~~~
      uv_process_options_s::args
/Users/danetag/.node-gyp/0.10.35/deps/uv/include/uv.h:1345:10: note: 
      'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:13:7: error: invalid use of non-static data member 'args'
  if (args.Length() < 1) {
      ^~~~
../csrc/addon.cc:14:14: error: no member named 'ThrowException' in
      'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:15:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Wrong number of arguments")));
        ~~~~~~~~^
../csrc/addon.cc:19:8: error: use of undeclared identifier 'args'; did you mean
      'uv_process_options_s::args'?
  if (!args[0]->IsObject()) {
       ^~~~
       uv_process_options_s::args
/Users/danetag/.node-gyp/0.10.35/deps/uv/include/uv.h:1345:10: note: 
      'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:19:8: error: invalid use of non-static data member 'args'
  if (!args[0]->IsObject()) {
       ^~~~
../csrc/addon.cc:20:14: error: no member named 'ThrowException' in
      'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:21:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Not an object")));
        ~~~~~~~~^
../csrc/addon.cc:25:31: error: use of undeclared identifier 'args'; did you
      mean 'uv_process_options_s::args'?
  Local<Object> inputBuffer = args[0]->ToObject();
                              ^~~~
                              uv_process_options_s::args
/Users/danetag/.node-gyp/0.10.35/deps/uv/include/uv.h:1345:10: note: 
      'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:25:31: error: invalid use of non-static data member 'args'
  Local<Object> inputBuffer = args[0]->ToObject();
                              ^~~~
../csrc/addon.cc:28:14: error: no member named 'ThrowException' in
      'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:29:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "First arg should be a Buffer")));
        ~~~~~~~~^
../csrc/addon.cc:45:14: error: no member named 'ThrowException' in
      'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:46:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Could not convert the given font.")));
        ~~~~~~~~^
../csrc/addon.cc:49:30: error: no matching function for call to 'New'
  Local<Object> slowBuffer = node::Buffer::New(isolate, output_length);
                             ^~~~~~~~~~~~~~~~~
/Users/danetag/.node-gyp/0.10.35/src/node_buffer.h:123:18: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'const char *' for 1st argument
  static Buffer* New(const char *data, size_t len);
                 ^
/Users/danetag/.node-gyp/0.10.35/src/node_buffer.h:116:33: note: candidate
      function not viable: requires single argument 'string', but 2 arguments
      were provided
  static v8::Handle<v8::Object> New(v8::Handle<v8::String> string);
                                ^
/Users/danetag/.node-gyp/0.10.35/src/node_buffer.h:121:18: note: candidate
      function not viable: requires single argument 'length', but 2 arguments
      were provided
  static Buffer* New(size_t length);
                 ^
/Users/danetag/.node-gyp/0.10.35/src/node_buffer.h:129:32: note: candidate
      function not viable: requires single argument 'args', but 2 arguments
      were provided
  static v8::Handle<v8::Value> New(const v8::Arguments &args);
                               ^
/Users/danetag/.node-gyp/0.10.35/src/node_buffer.h:125:18: note: candidate
      function not viable: requires 4 arguments, but 2 were provided
  static Buffer* New(char *data, size_t length,
                 ^
../csrc/addon.cc:52:38: error: no member named 'GetCurrentContext' in
      'v8::Isolate'
  Local<Object> globalObj = isolate->GetCurrentContext()->Global();
                            ~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/danetag/Sites/tests/screwdriver/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

```

**Comment by nfroidure** [comment]
Does your npm install exit with an error code? Run:

```sh
npm i
echo $?
```

Also, can you check if the following folder exists: node_modules/gulp-ttf2woff2/node_modules/ttf2woff2

Finally, is gulp-iconfon unusable, if so, what error does it throw, if not, are the woff2 fonts generated?

+OS + Node version

**Comment by Danetag** [comment]
```
Danetag-2:screwdriver danetag$ npm i
Danetag-2:screwdriver danetag$ echo $
0
```

Nope, no errors. The folder exists though.  

When I try to run the gulp-iconfont, I have the following error:

```
Danetag-2:screwdriver danetag$ gulp iconfonts
[10:34:58] Using gulpfile ~/Sites/tests/screwdriver/gulpfile.js
[10:34:58] Starting 'iconfonts'...

/Users/danetag/Sites/tests/screwdriver/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2/jssrc/ttf2woff2.js:90
      throw ex;
            ^
Error: ENOENT, open 'app/static/ui/iconfont/_iconfont.css'
```

OSX 10.10.3, Node v0.10.35

Thanks!

**Comment by nfroidure** [comment]
The echo $? command should be run separately ;). It prints the last command exit code.

But it just looks like the native add-on cannot compile on your system due to a too big amount of errors/warnings. Maybe that some cflags option could allow us to change this behavior, i'll try to look at it.

But anyway, since there is a JS fallback, it should work as espected (but slower).

The error you give seems unrelated but the stack trace is cutted so i can't be sure of that. It smells like you're using something to generate your CSS. Be aware that things changed between the 2.0.0 and 3.0.0 way to emit generated glyphs and it will certainly require you to change your templates a bit.

**Comment by Danetag** [comment]
Sorry :D If I run it separately, I have the following:

```
Danetag-2:screwdriver danetag$ npm i
Danetag-2:screwdriver danetag$ echo $
0
```

Looking closer to have the JS fallback working, thanks!
