### ISSUE TITLE
Install 3.0.2 Erroring

### ISSUE THREAD

**Issue by Psiablo** [nfroidure/gulp-iconfont#63]
Not sure if this is an error with gulp-iconfont or upstream.

Running `npm install gulp-iconfont --save-dev` gives me:

```
> ttf2woff2@1.1.0 install /Users/erictaylor/Projects/gulp/smartui/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc:9:20: error: unknown type name 'FunctionCallbackInfo'
void Convert(const FunctionCallbackInfo<Value>& args) {
                   ^
../csrc/addon.cc:9:40: error: expected ')'
void Convert(const FunctionCallbackInfo<Value>& args) {
                                       ^
../csrc/addon.cc:9:13: note: to match this '('
void Convert(const FunctionCallbackInfo<Value>& args) {
            ^
../csrc/addon.cc:11:15: error: no matching constructor for initialization of 'v8::HandleScope'
  HandleScope scope(isolate);
              ^     ~~~~~~~
/Users/erictaylor/.node-gyp/0.10.38/deps/v8/include/v8.h:473:3: note: candidate constructor not viable: no known conversion from 'v8::Isolate *' to 'const v8::HandleScope' for 1st argument
  HandleScope(const HandleScope&);
  ^
/Users/erictaylor/.node-gyp/0.10.38/deps/v8/include/v8.h:448:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  HandleScope();
  ^
../csrc/addon.cc:13:7: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1) {
      ^~~~
      uv_process_options_s::args
/Users/erictaylor/.node-gyp/0.10.38/deps/uv/include/uv.h:1345:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:13:7: error: invalid use of non-static data member 'args'
  if (args.Length() < 1) {
      ^~~~
../csrc/addon.cc:14:14: error: no member named 'ThrowException' in 'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:15:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Wrong number of arguments")));
        ~~~~~~~~^
../csrc/addon.cc:19:8: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (!args[0]->IsObject()) {
       ^~~~
       uv_process_options_s::args
/Users/erictaylor/.node-gyp/0.10.38/deps/uv/include/uv.h:1345:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:19:8: error: invalid use of non-static data member 'args'
  if (!args[0]->IsObject()) {
       ^~~~
../csrc/addon.cc:20:14: error: no member named 'ThrowException' in 'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:21:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Not an object")));
        ~~~~~~~~^
../csrc/addon.cc:25:31: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  Local<Object> inputBuffer = args[0]->ToObject();
                              ^~~~
                              uv_process_options_s::args
/Users/erictaylor/.node-gyp/0.10.38/deps/uv/include/uv.h:1345:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:25:31: error: invalid use of non-static data member 'args'
  Local<Object> inputBuffer = args[0]->ToObject();
                              ^~~~
../csrc/addon.cc:28:14: error: no member named 'ThrowException' in 'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:29:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "First arg should be a Buffer")));
        ~~~~~~~~^
../csrc/addon.cc:45:14: error: no member named 'ThrowException' in 'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:46:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Could not convert the given font.")));
        ~~~~~~~~^
../csrc/addon.cc:49:30: error: no matching function for call to 'New'
  Local<Object> slowBuffer = node::Buffer::New(isolate, output_length);
                             ^~~~~~~~~~~~~~~~~
/Users/erictaylor/.node-gyp/0.10.38/src/node_buffer.h:123:18: note: candidate function not viable: no known conversion from 'v8::Isolate *' to 'const char *' for 1st argument
  static Buffer* New(const char *data, size_t len);
                 ^
/Users/erictaylor/.node-gyp/0.10.38/src/node_buffer.h:116:33: note: candidate function not viable: requires single argument 'string', but 2 arguments were provided
  static v8::Handle<v8::Object> New(v8::Handle<v8::String> string);
                                ^
/Users/erictaylor/.node-gyp/0.10.38/src/node_buffer.h:121:18: note: candidate function not viable: requires single argument 'length', but 2 arguments were provided
  static Buffer* New(size_t length);
                 ^
/Users/erictaylor/.node-gyp/0.10.38/src/node_buffer.h:129:32: note: candidate function not viable: requires single argument 'args', but 2 arguments were provided
  static v8::Handle<v8::Value> New(const v8::Arguments &args);
                               ^
/Users/erictaylor/.node-gyp/0.10.38/src/node_buffer.h:125:18: note: candidate function not viable: requires 4 arguments, but 2 were provided
  static Buffer* New(char *data, size_t length,
                 ^
../csrc/addon.cc:52:38: error: no member named 'GetCurrentContext' in 'v8::Isolate'
  Local<Object> globalObj = isolate->GetCurrentContext()->Global();
                            ~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by nfroidure** [comment]
https://github.com/nfroidure/gulp-iconfont/issues/60

**Comment by nfroidure** [comment]
@Psiablo  @Danetag

Would some of you clone the [ttf2woff2](https://github.com/nfroidure/ttf2woff2) repo, add `-ferror-limit=0` in the cflags here: https://github.com/nfroidure/ttf2woff2/blob/master/binding.gyp#L28 and run `npm run configure && npm run make` in the project folder to see if it solve the compilation issue on MacOSX? If so, please PR ;).

**Comment by nfroidure** [comment]
Also, could you give me your node version ?
```
node -v
```
If it is 0.10, the compilation errors are normal, upgrade to 0.12+ to get the native version compiled.

**Comment by Psiablo** [comment]
@nfroidure cloned repo, added `-ferror-limit=0` to cflags. Ran `npm run configure && npm run make` Resulted:
```
~/Github/ttf2woff2 [ferrorlimit]✎ erictaylor@Daxos-Pro 0.2677s
❯ npm -v
2.11.2
                                                                                                                                                                                                                                                                                                                              
~/Github/ttf2woff2 [ferrorlimit]✎ erictaylor@Daxos-Pro 0.4579s
❯ npm run configure && npm run make

> ttf2woff2@1.1.0 configure /Users/erictaylor/Github/ttf2woff2
> node-gyp configure


> ttf2woff2@1.1.0 make /Users/erictaylor/Github/ttf2woff2
> node-gyp build

  CXX(target) Release/obj.target/addon/csrc/addon.o
  CXX(target) Release/obj.target/addon/csrc/woff2/glyph.o
../csrc/woff2/glyph.cc:125:25: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
      for (int j = 0; j < glyph->contours[i].size(); ++j) {
                      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
../csrc/woff2/glyph.cc:146:25: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
      for (int j = 0; j < glyph->contours[i].size(); ++j) {
                      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
../csrc/woff2/glyph.cc:173:25: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
      for (int j = 0; j < glyph->contours[i].size(); ++j) {
                      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
../csrc/woff2/glyph.cc:235:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& contour : glyph.contours) {
             ^
../csrc/woff2/glyph.cc:235:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& contour : glyph.contours) {
                           ^
../csrc/woff2/glyph.cc:256:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& contour : glyph.contours) {
             ^
../csrc/woff2/glyph.cc:256:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& contour : glyph.contours) {
                           ^
../csrc/woff2/glyph.cc:257:16: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (const auto& point : contour) {
               ^
../csrc/woff2/glyph.cc:257:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const auto& point : contour) {
                           ^
../csrc/woff2/glyph.cc:314:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& contour : glyph.contours) {
             ^
../csrc/woff2/glyph.cc:314:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& contour : glyph.contours) {
                           ^
../csrc/woff2/glyph.cc:315:16: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (const auto& point : contour) {
               ^
../csrc/woff2/glyph.cc:315:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const auto& point : contour) {
                           ^
../csrc/woff2/glyph.cc:359:31: warning: comparison of integers of different signs: 'size_type' (aka 'unsigned long') and 'short' [-Wsign-compare]
    if (glyph.contours.size() > std::numeric_limits<int16_t>::max()) {
        ~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14 warnings generated.
  CXX(target) Release/obj.target/addon/csrc/woff2/font.o
../csrc/woff2/font.cc:42:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : tables) {
             ^
../csrc/woff2/font.cc:42:22: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : tables) {
                     ^
../csrc/woff2/font.cc:104:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : intervals) {
             ^
../csrc/woff2/font.cc:104:22: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : intervals) {
                     ^
../csrc/woff2/font.cc:124:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto& entry : font->tables) {
       ^
../csrc/woff2/font.cc:124:20: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto& entry : font->tables) {
                   ^
../csrc/woff2/font.cc:147:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto i = 0; i < num_fonts; i++) {
         ^
../csrc/woff2/font.cc:159:16: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (const auto offset : offsets) {
               ^
../csrc/woff2/font.cc:159:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const auto offset : offsets) {
                           ^
../csrc/woff2/font.cc:147:24: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
    for (auto i = 0; i < num_fonts; i++) {
                     ~ ^ ~~~~~~~~~
../csrc/woff2/font.cc:203:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : font.tables) {
             ^
../csrc/woff2/font.cc:203:22: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : font.tables) {
                     ^
../csrc/woff2/font.cc:214:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto& font : font_collection.fonts) {
       ^
../csrc/woff2/font.cc:214:19: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto& font : font_collection.fonts) {
                  ^
../csrc/woff2/font.cc:278:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : font.tables) {
             ^
../csrc/woff2/font.cc:278:22: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : font.tables) {
                     ^
../csrc/woff2/font.cc:315:11: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    const auto& font = font_collection.fonts[i];
          ^
../csrc/woff2/font.cc:303:21: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
  for (int i = 0; i < font_collection.fonts.size(); i++) {
                  ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../csrc/woff2/font.cc:314:21: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
  for (int i = 0; i < font_collection.fonts.size(); i++) {
                  ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19 warnings generated.
  CXX(target) Release/obj.target/addon/csrc/woff2/normalize.o
../csrc/woff2/normalize.cc:177:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto tag : font->OutputOrderedTags()) {
       ^
../csrc/woff2/normalize.cc:177:17: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto tag : font->OutputOrderedTags()) {
                ^
../csrc/woff2/normalize.cc:178:5: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    auto& table = font->tables[tag];
    ^
../csrc/woff2/normalize.cc:194:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : font.tables) {
             ^
../csrc/woff2/normalize.cc:194:22: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& i : font.tables) {
                     ^
../csrc/woff2/normalize.cc:226:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto& i : font->tables) {
       ^
../csrc/woff2/normalize.cc:226:16: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto& i : font->tables) {
               ^
../csrc/woff2/normalize.cc:287:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto& font : font_collection->fonts) {
       ^
../csrc/woff2/normalize.cc:287:19: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto& font : font_collection->fonts) {
                  ^
../csrc/woff2/normalize.cc:296:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto& font : font_collection->fonts) {
       ^
../csrc/woff2/normalize.cc:296:19: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto& font : font_collection->fonts) {
                  ^
../csrc/woff2/normalize.cc:297:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto tag : font.OutputOrderedTags()) {
         ^
../csrc/woff2/normalize.cc:297:19: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (auto tag : font.OutputOrderedTags()) {
                  ^
../csrc/woff2/normalize.cc:309:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto& font : font_collection->fonts) {
       ^
../csrc/woff2/normalize.cc:309:19: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto& font : font_collection->fonts) {
                  ^
15 warnings generated.
  CXX(target) Release/obj.target/addon/csrc/woff2/table_tags.o
  CXX(target) Release/obj.target/addon/csrc/woff2/transform.o
../csrc/woff2/transform.cc:42:21: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
  for (int i = 0; i < in.size(); ++i) {
                  ~ ^ ~~~~~~~~~
../csrc/woff2/transform.cc:116:16: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (const auto& contour : glyph.contours) {
               ^
../csrc/woff2/transform.cc:116:30: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const auto& contour : glyph.contours) {
                             ^
../csrc/woff2/transform.cc:117:18: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
      for (const auto& point : contour) {
                 ^
../csrc/woff2/transform.cc:117:30: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
      for (const auto& point : contour) {
                             ^
../csrc/woff2/transform.cc:31:11: warning: unused variable 'FLAG_ARG_1_AND_2_ARE_WORDS' [-Wunused-const-variable]
const int FLAG_ARG_1_AND_2_ARE_WORDS = 1 << 0;
          ^
../csrc/woff2/transform.cc:32:11: warning: unused variable 'FLAG_WE_HAVE_INSTRUCTIONS' [-Wunused-const-variable]
const int FLAG_WE_HAVE_INSTRUCTIONS = 1 << 8;
          ^
7 warnings generated.
  CXX(target) Release/obj.target/addon/csrc/woff2/variable_length.o
../csrc/woff2/variable_length.cc:52:20: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (uint8_t val : packed) {
                   ^
../csrc/woff2/variable_length.cc:123:21: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  for (int i = 0; i < size; ++i) {
                  ~ ^ ~~~~
../csrc/woff2/variable_length.cc:125:11: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
    if (i < size - 1) {
        ~ ^ ~~~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/addon/csrc/woff2/woff2_common.o
  CXX(target) Release/obj.target/addon/csrc/woff2/woff2_enc.o
In file included from ../csrc/woff2/woff2_enc.cc:27:
In file included from ../csrc/woff2/./../enc/encode.h:25:
In file included from ../csrc/woff2/./../enc/./hash.h:35:
../csrc/woff2/./../enc/./static_dict.h:21:10: fatal error: 'unordered_map' file not found
#include <unordered_map>
         ^
1 error generated.
make: *** [Release/obj.target/addon/csrc/woff2/woff2_enc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/erictaylor/.nvm/versions/node/v0.12.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/erictaylor/.nvm/versions/node/v0.12.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/erictaylor/Github/ttf2woff2
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/erictaylor/.nvm/versions/node/v0.12.5/bin/node" "/Users/erictaylor/.nvm/versions/node/v0.12.5/bin/npm" "run" "make"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! ttf2woff2@1.1.0 make: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ttf2woff2@1.1.0 make script 'node-gyp build'.
npm ERR! This is most likely a problem with the ttf2woff2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ttf2woff2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erictaylor/Github/ttf2woff2/npm-debug.log
```

**Comment by Psiablo** [comment]
```
❯ npm run configure && npm run make

> ttf2woff2@1.1.0 configure /Users/erictaylor/Github/ttf2woff2
> node-gyp configure


> ttf2woff2@1.1.0 make /Users/erictaylor/Github/ttf2woff2
> node-gyp build

  CXX(target) Release/obj.target/addon/csrc/woff2/woff2_enc.o
In file included from ../csrc/woff2/woff2_enc.cc:27:
In file included from ../csrc/woff2/./../enc/encode.h:25:
In file included from ../csrc/woff2/./../enc/./hash.h:35:
../csrc/woff2/./../enc/./static_dict.h:21:10: fatal error: 'unordered_map' file not found
#include <unordered_map>
         ^
1 error generated.
make: *** [Release/obj.target/addon/csrc/woff2/woff2_enc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/erictaylor/.nvm/versions/node/v0.12.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/erictaylor/.nvm/versions/node/v0.12.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/erictaylor/Github/ttf2woff2
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/erictaylor/.nvm/versions/node/v0.12.5/bin/node" "/Users/erictaylor/.nvm/versions/node/v0.12.5/bin/npm" "run" "make"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! ttf2woff2@1.1.0 make: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ttf2woff2@1.1.0 make script 'node-gyp build'.
npm ERR! This is most likely a problem with the ttf2woff2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ttf2woff2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erictaylor/Github/ttf2woff2/npm-debug.log
```

**Comment by nfroidure** [comment]
Ok, so your GCC version seems too old, you'll have to use the JS fallback :(. http://stackoverflow.com/questions/18548872/using-c11-unordered-map-types-on-mac-os-x

Chances are i'll have a look at it to try to make it faster soon.

**Comment by Psiablo** [comment]
Excuse my ignorance, but why can't I just clone the woff2 repo from Google, build `woff2_compress`, include it in my path, and then have gulp-iconfont have a option to use woff2 or not which just executes `woff2_compress` on the font file. Why do we rely on a modified version of `woff2_compress` that has stdout?

**Comment by nfroidure** [comment]
In order to be able to stream the woff2_compress i/o with Gulp. Writing temprorary files to the disk would be really slower.

**Comment by nfroidure** [comment]
In fact, you can also use the spawnWoff2 option and to compile my woff2 fork and put woff2_compress in your actuel PATH.

**Comment by Psiablo** [comment]
All your doing is basically self including a modified version of `woff2` inside of `ttf2woff2` correct (modified meaning includes stdout for gulp streaming consumption)? I guess I'm confused as to why it has a problem building, if I can build `woff2` myself just fine.

I can pull Google's repo and build `woff2_compress` just fine with no error. So what is so different about what you are packaging that makes it not build with the included gcc version on Mac OS X?

So if the problem for me is this file: https://github.com/nfroidure/ttf2woff2/blob/master/csrc/enc/static_dict.h

Why is that file so different from:
https://github.com/google/brotli/blob/master/enc/static_dict.h

**Comment by Psiablo** [comment]
https://github.com/google/woff2/blob/master/Makefile line 11 related?

**Comment by nfroidure** [comment]
There are 2 ways to use native woff2 sources:
- **you** build the binaries and put it in your PATH using my woff2 temporary fork https://github.com/nfroidure/woff2 for the reasons i mentioned earlyer. If so, and if the spawnWOFF2 flag is set to true, it wiull be done there:  https://github.com/nfroidure/gulp-iconfont/blob/master/src/index.js#L78
- **node** build a native driver from this wrapper https://github.com/nfroidure/ttf2woff2/blob/master/csrc/addon.cc and we try to dynamically load it there: https://github.com/nfroidure/ttf2woff2/blob/master/src/index.js#L2

All of it fallbacks to the emscripten build **i** prepared for you ;).

To be honest, i don't exactly know why node can't build the addon on OSX and i don't really care since i won't be able to test it by myself. The fact is that it still work if the addon compilation fails and it's fair enough for me since i don't plan to buy a mac to power it only one time for testing this build ;).

Chances are this repo is open source so you or someone else can submit a PR that fix it.

**Comment by nfroidure** [comment]
@Psiablo try to add this flag to cflags and if it work let me know or PR ttf2woff2
